### ISSUE TITLE
JPG: "Image given has not completed loading"

### ISSUE THREAD

**Issue by lapidus** [meltingice/CamanJS#213]
I am experiencing a somewhat odd issue ... 
For JPG images (such as the attached one) that was downloaded with nodejs (fs.writeFile), Caman gives this error:
```
Image given has not completed loading
    at Caman.finishInit /node_modules/caman/dist/caman.full.js:463:22
    at Caman.nodeFileReady /node_modules/caman/dist/caman.full.js:372:19
    at node_modules/caman/dist/caman.full.js:7:61
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:416:3)
```

If I open this image in the browser and resave it, Caman will not produce any errors. Hence I suspect there is some kind of "JPG header" that Caman needs to interpret the JPG properly? 
Did anyone else try Caman on a .jpg that was created via fs.writefile? Any ideas appreciated ...

![0ab695ba-6994-11d7-ae76-0004755038ce](https://cloud.githubusercontent.com/assets/66601/23009092/94d28950-f446-11e6-8dc1-554176cc7a8f.jpg)

**Comment by kakaggarwal** [comment]
Is anyone working on this ?
